<?php
/**
 * Appmerce - Applications for Ecommerce
 * http://www.appmerce.com
 *
 * @extension   Stripe
 * @type        Payment method
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Magento
 * @package     Appmerce_Stripe
 * @copyright   Copyright (c) 2011-2019 Appmerce (http://www.appmerce.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$acceptedCards = Mage::getStoreConfig('payment/stripe_cc/cctype');
?>

<link rel="stylesheet" href="/skin/frontend/base/default/css/appmerce/stripe/styles.css">
<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <input type="hidden" name="stripeToken" id="stripe_token">
    <div id="stripe-error-messages"></div>
    <ol id="stripe-cards-select-new">
        <li>
            <label for="stripe_cc_number" class="appmerce-label_placeholder"><?php echo $this->__('Card Number'); ?></label>
            <input id="stripe_cc_number" type="tel" x-autocompletetype="cc-number" autocompletetype="cc-number" autocorrect="off" spellcheck="off" autocapitalize="off" placeholder="<?php echo $this->__('Card Number'); ?>" data-stripe="number" size="20">
        </li>
        <li class="appmerce-float">
            <label for="stripe_cc_exp" class="appmerce-label_placeholder"><?php echo $this->__('Expiry Date'); ?></label>
            <input id="stripe_cc_exp" type="tel" x-autocompletetype="off" autocompletetype="off" autocorrect="off" spellcheck="off" autocapitalize="off" placeholder="MM / YY" size="5" data-stripe="exp">
        </li>
        <li class="appmerce-float">
            <label for="stripe_cc_cvc" class="appmerce-label_placeholder"><?php echo $this->__('CVC'); ?></label>
            <input id="stripe_cc_cvc" type="tel" autocomplete="off" autocorrect="off" spellcheck="off" autocapitalize="off" placeholder="<?php echo $this->__('CVC'); ?>" data-stripe="cvc" size="4" maxlength="4">
        </li>
    </ol>
</div>

<script>

    Stripe.setPublishableKey('<?php echo Mage::getStoreConfig('payment/stripe_cc/api_publishable_key'); ?>');

    (function() {
        appmerce.stripeCc.init('<?php echo $acceptedCards; ?>');
    })();

</script>
